swagger: "2.0"
info:
  version: "1.0.0"
  title: "Product service API"
host: 3w5dmw8tz3.execute-api.eu-west-1.amazonaws.com
basePath: /dev 
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /products:
    get:
      description: Returns the array of existing products
      produces:
      - application/json
      responses:
        '200':
          description: Array of existing products with prices
    post:
      description: Returns single product based on productID(CORS sensitive, not available from localhost)
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          description: API to create product.
          schema:
            type: object
            required:
              - id
              - description
              - title
              - price
              - count
            properties:
              id:
                type: string
              description:
                type: string
              title:
                type: string
              price:
                type: string
              count:
                type: string      
      produces:
      - application/json
      responses:
        '200':
          description: Single product from the database.         
  /products/{id}:
    get:
      description: Returns single product based on productID
      produces:
      - application/json
      responses:
        '200':
          description: Single product from the database.
        default:
          description: Unexpected error if productID is missing or was not provided
    parameters:
      - name: id
        in: path
        description: ID of the product
        required: true
        type: string      
              